CREATE TABLE IF NOT EXISTS userRegister (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
	Nickname TEXT NOT NULL UNIQUE,
	Age INTEGER NOT NULL,
	Gender TEXT NOT NULL,
	FirstName TEXT NOT NULL,
	LastName TEXT NOT NULL,
	Email TEXT NOT NULL UNIQUE,
	Password TEXT NOT NULL
)