CREATE TABLE IF NOT EXISTS userRegister (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
	nickname TEXT NOT NULL,
	age INTEGER NOT NULL,
	gender TEXT NOT NULL,
	firstName TEXT NOT NULL,
	lastName TEXT NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL
)