CREATE TABLE IF NOT EXISTS Comments (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
	Comment TEXT NOT NULL,
	Post_id INTEGER ,
	User_id INTEGER ,
	Like INTEGER ,
	Dislike INTEGER ,
	FOREIGN KEY (Post_id) REFERENCES Post (Id)
)