CREATE TABLE IF NOT EXISTS UserPosts (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
	UserId TEXT ,
	Title TEXT NOT NULL,
	Image BLOB ,
	Content TEXT NOT NULL,
	Like INTEGER ,
	Dislike INTEGER 
)