CREATE TABLE IF NOT EXISTS UserPosts (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
	Title TEXT NOT NULL,
	Image  ,
	Content TEXT NOT NULL,
	Like INTEGER ,
	Dislike INTEGER 
)